[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "tenant-advocate-rag"
version = "0.0.1"
description = "An end-to-end Agentic RAG application that empowers renters to understand their legal rights. The system allows users to upload their lease agreements, ask questions in plain English, and receive legally grounded summaries cross-referenced against state tenancy laws."
authors = [
  { name = "Gourika" },
]

readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    
]
requires-python = "~=3.11.0"


[tool.ruff]
line-length = 99
src = ["tenant-advocate-rag"]
include = ["pyproject.toml", "tenant-advocate-rag/**/*.py"]

[tool.ruff.lint]
extend-select = ["I"]  # Add import sorting

[tool.ruff.lint.isort]
known-first-party = ["tenant-advocate-rag"]
force-sort-within-sections = true

